using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Animal_Crossing_Text_Editor.Classes.Parser.Command
{
    public enum ControlCode
    {
        EndConversation,
        JumpToNextDialog,
        ClearPage,
        Pause,
        PressButton,
        LineColor,
        SkippableText,
        UnskippableText,
        SetDemoOrderPlayer,
        SetDemoOrderNpc0,
        SetDemoOrderNpc1,
        SetDemoOrderNpc2,
        SetDemoOrderQuest,
        ShowChoiceMenu,
        SetNextMessageForced,
        SetNextMessage0,
        SetNextMessage1,
        SetNextMessage2,
        SetNextMessage3,
        SetNextMessageRandom2,
        SetNextMessageRandom3,
        SetNextMessageRandom4,
        SetSelectString2,
        SetSelectString3,
        SetSelectString4,
        SetForceNext,
        PutStringPlayerName,
        PutStringTalkName,
        PutStringTail,
        PutStringYear,
        PutStringMonth,
        PutStringWeek,
        PutStringDay,
        PutStringHour,
        PutStringMinute,
        PutStringSecond,
        PutStringFree0,
        PutStringFree1,
        PutStringFree2,
        PutStringFree3,
        PutStringFree4,
        PutStringFree5,
        PutStringFree6,
        PutStringFree7,
        PutStringFree8,
        PutStringFree9,
        PutStringDetermination,
        PutStringCountryName,
        PutStringRandomNumber2,
        PutStringItem0,
        PutStringItem1,
        PutStringItem2,
        PutStringItem3,
        PutStringItem4,
        PutStringFree10,
        PutStringFree11,
        PutStringFree12,
        PutStringFree13,
        PutStringFree14,
        PutStringFree15,
        PutStringFree16,
        PutStringFree17,
        PutStringFree18,
        PutStringFree19,
        PutStringMail,
        SetPlayerDestiny0,
        SetPlayerDestiny1,
        SetPlayerDestiny2,
        SetPlayerDestiny3,
        SetPlayerDestiny4,
        SetPlayerDestiny5,
        SetPlayerDestiny6,
        SetPlayerDestiny7,
        SetPlayerDestiny8,
        SetPlayerDestiny9,
        SetMessageContentsNormal,
        SetMessageContentsAngry,
        SetMessageContentsSad,
        SetMessageContentsFun,
        SetMessageContentsSleepy,
        SetColorChar,
        SoundCut,
        SetLineOffset,
        SetLineType,
        SetCharScale,
        Button2,
        BgmMake,
        BgmDelete,
        MsgTimeEnd,
        SoundTrgSys,
        SetLineScale,
        SoundNoPage,
        VoiceTrue,
        VoiceFalse,
        SelectNoB,
        GiveOpen,
        GiveClose,
        SetMessageConttentsGloomy,
        SelectNoBClose,
        SetNextMessageRandomSection,
        AgbDummy,
        Space = 0x67,
        MaleFemaleCheck = 0x6A,
        PutStringIslandName = 0x71,
        SetCusrorJust = 0x72,
        ClrCursorJust = 0x73,
        CutArticle = 0x74,
        // AC+ only
        CapitalLetter = 0x75,
        PutStringAmPm = 0x76,
        SetNextMessage4 = 0x77,
        SetNextMessage5 = 0x78,
        SetSelectString5 = 0x79,
        SetSelectString6 = 0x7A,
        // DnMe+ only
        NineBit = 0x7B,
        FontKigou = 0x7C
    }
}
